#!/bin/bash

function die {
    printf >&2 '%s: %s.\n' "$0" "$1"
    exit 1
}

function usage {
    printf 'Usage: %s [--exclude PATTERN | --include PATTERN | --no-default-excludes | --user | --system | --do-restart | --no-do-restart]...\n' "$0"
}

function die-with-usage {
    if (($#)); then
        printf >&2 '%s: %s.\n' "$0" "$1"
    fi
    usage >&2
    exit 1
}

# associative arrays from pattern to selection function
# true: select if not overridden by false for other matching pattern
# false: never select;
# exclude-*-by-default: don’t select, but trumped by “true” for other matching patterns and can be changed to mean select-*-by-default via --no-default-*-excludes
declare -A selectUnitName=(
    ['*.socket']=exclude-unit-name-by-default
    ['*.target']=exclude-unit-name-by-default
    ['*.device']=exclude-unit-name-by-default
    ['*.mount']=exclude-unit-name-by-default
    ['*.automount']=exclude-unit-name-by-default
    ['*.timer']=exclude-unit-name-by-default
    ['*.swap']=exclude-unit-name-by-default
    ['*.path']=exclude-unit-name-by-default
    ['*.slice']=exclude-unit-name-by-default
    ['*.scope']=exclude-unit-name-by-default
    ['user@*.service']=exclude-unit-name-by-default
)
declare -A selectPath=(
    ['/dev/zero']=exclude-path-by-default
    ['/SYSV*']=exclude-path-by-default
)
function exclude-unit-name-by-default { false; }
function exclude-path-by-default { false; }
function select-unit-name-by-default { true; }
function select-path-by-default { true; }

mode=--system

function do-restart {
    case $mode in
        --system)
            if ((UID==0)); then true; else false; fi;;
        --user)
            false;;
        *)
            die 'Unknown mode';;
    esac
}

while (($#)); do
    case $1 in
        --exclude-unit-name)
            if [[ -n "$2" ]]; then
                selectUnitName["$2"]=false
            else
                die-with-usage 'Missing --exclude-unit-name argument'
            fi
            shift 2
            ;;
        --include-unit-name)
            if [[ -n "$2" ]]; then
                selectUnitName["$2"]=true
                function select-unit-name-by-default { false; }
            else
                die-with-usage 'Missing --include-unit-name argument'
            fi
            shift 2
            ;;
        --exclude-path)
            if [[ -n "$2" ]]; then
                selectPath["$2"]=false
            else
                die-with-usage 'Missing --exclude-path argument'
            fi
            shift 2
            ;;
        --include-path)
            if [[ -n "$2" ]]; then
                selectPath["$2"]=true
                function select-path-by-default { false; }
            else
                die-with-usage 'Missing --include-path argument'
            fi
            shift 2
            ;;
        --no-default-unit-name-excludes)
            function exclude-unit-name-by-default { select-unit-name-by-default; }
            shift 1
            ;;
        --no-default-path-excludes)
            function exclude-path-by-default { select-path-by-default; }
            shift 1
            ;;
        --system|--user)
            mode="$1"
            shift 1
            ;;
        --do-restart)
            function do-restart { true; }
            shift 1
            ;;
        --no-do-restart)
            function do-restart { false; }
            shift 1
            ;;
        --help) usage; exit;;
        -*) die-with-usage 'Unknown option';;
        *) die-with-usage 'Unexpected argument';;
    esac
done

function busctl {
    command busctl "$mode" "$@"
}

exec 3< <(lsof -n -F pnf)
declare -i pid=0
declare -a pids=()
declare fd path
function process-file-set {
    # if pid, fd or path are not yet initialized, ignore
    if [[ -z "$pid" || -z "$fd" || -z "$path" ]]; then
        return
    fi
    # if pid is already in pids, ignore
    if ((${#pids[@]} != 0)) && [[ "${pids[-1]}" == "$pid" ]]; then
        return
    fi
    # if file descriptor is not DEL, ignore
    if [[ "$fd" != "DEL" ]]; then
        return
    fi
    # if path is not selected, ignore
    selection=select-path-by-default
    for pattern in "${!selectPath[@]}"; do
        newSelection="${selectPath[$pattern]}"
        if [[ "$path" == $pattern ]]; then
            if [[ "$selection" == false ]]; then
                continue # cannot be overridden
            elif [[ "$newSelection" == false ]]; then
                selection="$newSelection" # overrides everything
            elif [[ "$selection" == *-by-default ]]; then
                selection="$newSelection" # overridden by everything
            fi
        fi
    done
    if ! "$selection"; then
        return
    fi
    # add to pids
    pids+=("$pid")
}
# lsof outputs “process sets” (start with p field) and then “file sets” per process set (start with f field).
# Within the file sets, the order of fields seems to be arbitrary;
# we have to defer acting upon them until the file set is over (next p or f field).
while IFS= read -r field; do
    case $field in
        p*)
            process-file-set
            pid=${field:1}
            ;;
        f*)
            process-file-set
            fd=${field:1}
            ;;
        n*)
            path=${field:1}
            ;;
        *) die 'Unexpected lsof output';;
    esac
done <&3

declare -a units=()
for pid in "${pids[@]}"; do
    unitOut=$(busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnitByPID u "$pid" 2>&1)
    (($? == 0)) || {
        # print error message unless it’s “unknown PID” in --user mode, which is expected
        if ! [[ "$unitOut" == "PID $pid does not belong to any loaded unit." && "$mode" == "--user" ]]; then
            printf >&2 '%s\n' "$unitOut"
        fi
        continue
    }
    IFS=' ' read -r type path rest <<< "$unitOut"
    [[ -z "$rest" ]] || die 'Unexpected GetUnitByPID trailing output'
    [[ "$type" == "o" ]] || die 'Unexpected GetUnitByPID return type'
    [[ "$path" == '"'*'"' ]] || die 'Unquoted path returned by GetUnitByPID'
    unit="${path:1:-1}"
    store=true
    for savedUnit in "${units[@]}"; do
        if [[ "$savedUnit" == "$unit" ]]; then
            store=false
            break
        fi
    done
    if "$store"; then
        units+=("$unit")
    fi
done

declare -A unitNames=()
for unitObject in "${units[@]}"; do
    unitNameOut=$(busctl get-property org.freedesktop.systemd1 "$unitObject" org.freedesktop.systemd1.Unit Id)
    (($? == 0)) || unitNames[$unitObject]=""
    IFS=' ' read -r type id rest <<< "$unitNameOut"
    [[ -z "$rest" ]] || die 'Unexpected Id trailing output'
    [[ "$type" == "s" ]] || die 'Unexpected Id type'
    [[ "$id" == '"'*'"' ]] || die 'Unquoted Id'
    name="${id:1:-1}"
    unitNames[$unitObject]="$name"
done

declare -A selectedUnitNames=()
for unitObject in "${!unitNames[@]}"; do
    unitName="${unitNames[$unitObject]}"
    selection=select-unit-name-by-default
    for pattern in "${!selectUnitName[@]}"; do
        newSelection="${selectUnitName[$pattern]}"
        if [[ "$unitName" == $pattern ]]; then
            if [[ "$selection" == false ]]; then
                continue # cannot be overridden
            elif [[ "$newSelection" == false ]]; then
                selection="$newSelection" # overrides everything
            elif [[ "$selection" == *-by-default ]]; then
                selection="$newSelection" # overridden by everything
            fi
        fi
    done
    if "$selection"; then
        selectedUnitNames[$unitObject]="$unitName"
    fi
done

if ((${#selectedUnitNames[@]})); then
    declare s theseUnits # pluralization
    if ((${#selectedUnitNames[@]}>1)); then
        s="s"
        theseUnits="these units"
    else
        s=""
        theseUnits="this unit"
    fi
    printf 'Found %d unit%s using deleted files:\n' "${#selectedUnitNames[@]}" "$s"
    printf '%s\n' "${selectedUnitNames[@]}"
    
    if do-restart; then
        read -r -N1 -p "Do you want to restart $theseUnits? [y/N] " doRestart
        [[ -z "$doRestart" ]] || printf '\n'
        case $doRestart in
            y|Y) ;;
            n|N) exit;;
            *) exit;;
        esac
    else
        exit
    fi
    systemctl "$mode" restart -- "${selectedUnitNames[@]}"
else
    printf 'Found 0 units using deleted files.\n'
fi
