#!/bin/bash

function die {
    printf >&2 '%s: %s.\n' "$0" "$1"
    exit 1
}

exec 3< <(lsof -F pf)
declare -i pid=0
declare -a pids=()
while IFS= read -r field; do
    case $field in
        p*) pid=${field:1};;
        f*) [[ "${field:1}" == "DEL" && (${#pids[@]} == 0 || ${pids[-1]} != "$pid") ]] && pids+=("$pid");;
        *) die 'Unexpected lsof output';;
    esac
done <&3

declare -a units=()
for pid in "${pids[@]}"; do
    unitOut=$(busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnitByPID u "$pid")
    (($? == 0)) || continue
    IFS=' ' read -r type path rest <<< "$unitOut"
    [[ -z "$rest" ]] || die 'Unexpected GetUnitByPID trailing output'
    [[ "$type" == "o" ]] || die 'Unexpected GetUnitByPID return type'
    [[ "$path" == '"'*'"' ]] || die 'Unquoted path returned by GetUnitByPID'
    unit="${path:1:-1}"
    store=true
    for savedUnit in "${units[@]}"; do
        if [[ "$savedUnit" == "$unit" ]]; then
            store=false
            break
        fi
    done
    if "$store"; then
        units+=("$unit")
    fi
done

printf 'Found %d units using deleted files:\n' "${#units[@]}"
printf '%s\n' "${units[@]}"
